CREATE TABLE irs_8872 (
	form_type INTEGER, 
	form_id_num VARCHAR(38) PRIMARY KEY, 
	period_begin_date VARCHAR(8), 
	period_end_date VARCHAR(8), 
	initial_report BOOLEAN, 
	amended_report BOOLEAN, 
	final_report BOOLEAN, 
	change_of_address BOOLEAN, 
	organization_name VARCHAR(70), 
        ein VARCHAR(9), 
	mailing_address_1 VARCHAR(50), 
	mailing_address_2 VARCHAR(50), 
	mailing_address_city VARCHAR(50), 
	mailing_address_state VARCHAR(2), 
	mailing_address_zip VARCHAR(5), 
	mailing_address_zip_ext VARCHAR(4), 
	email VARCHAR(150), 
	org_formation_date VARCHAR(8), 
	custodian_name VARCHAR(50), 
	custodian_address_1 VARCHAR(50), 
	custodian_address_2 VARCHAR(50), 
	custodian_address_city VARCHAR(50), 
	custodian_address_state VARCHAR(2), 
	custodian_address_zip VARCHAR(5), 
	custodian_address_zip_ext VARCHAR(4), 
	contact_person_name VARCHAR(50), 
	contact_address_1 VARCHAR(50), 
	contact_address_2 VARCHAR(50), 
	contact_address_city VARCHAR(50), 
	contact_address_state VARCHAR(2), 
	contact_address_zip VARCHAR(5), 
	contact_address_zip_ext VARCHAR(4), 
	business_address_1 VARCHAR(50), 
	business_address_2 VARCHAR(50), 
	business_address_city VARCHAR(50), 
	business_address_state VARCHAR(2), 
	business_address_zip VARCHAR(5), 
	business_address_zip_ext VARCHAR(4), 
	qtr_indicator INTEGER, 
	monthly_rpt_month VARCHAR, 
	pre_elect_type VARCHAR, 
	pre_or_post_elect_date VARCHAR(8), 
	pre_or_post_elect_state VARCHAR(2),
        sched_a_ind BOOLEAN, 
	total_sched_a DOUBLE PRECISION, 
	sched_b_ind INTEGER, 
	total_sched_b DOUBLE PRECISION, 
	insert_datetime TIMESTAMP WITHOUT TIME ZONE,
        empty_field VARCHAR(2)
);
