CREATE TABLE irs_8871 (
	form_type INTEGER, 
	form_id_num VARCHAR(38) PRIMARY KEY, 
	initial_report BOOLEAN, 
	amended_report BOOLEAN, 
	final_report BOOLEAN, 
	ein VARCHAR(9), 
	organization_name VARCHAR(70), 
	mailing_address_1 VARCHAR(50), 
	mailing_address_2 VARCHAR(50), 
	mailing_address_city VARCHAR(50), 
	mailing_address_state VARCHAR(2), 
	mailing_address_zip VARCHAR(5), 
	mailing_address_zip_ext VARCHAR(4), 
	email VARCHAR(150), 
	established_date VARCHAR(8), 
	custodian_name VARCHAR(50), 
	custodian_address_1 VARCHAR(50), 
	custodian_address_2 VARCHAR(50), 
	custodian_address_city VARCHAR(50), 
	custodian_address_state VARCHAR(2), 
	custodian_address_zip VARCHAR(5), 
	custodian_address_zip_ext VARCHAR(4), 
	contact_person_name VARCHAR(50), 
	contact_address_1 VARCHAR(50), 
	contact_address_2 VARCHAR(50), 
	contact_address_city VARCHAR(50), 
	contact_address_state VARCHAR(2), 
	contact_address_zip VARCHAR(5), 
	contact_address_zip_ext VARCHAR(4), 
	business_address_1 VARCHAR(50), 
	business_address_2 VARCHAR(50), 
	business_address_city VARCHAR(50), 
	business_address_state VARCHAR(2), 
	business_address_zip VARCHAR(5), 
	business_address_zip_ext VARCHAR(4), 
	exempt_8872 BOOLEAN, 
	exempt_state VARCHAR(2), 
	exempt_990 BOOLEAN, 
	purpose TEXT, 
	material_change_date VARCHAR(8), 
	insert_datetime TIMESTAMP WITHOUT TIME ZONE, 
	related_entity_bypass BOOLEAN,
	eain_bypass BOOLEAN
);
